### ISSUE TITLE
Even after using :CondaActivate, the langauge server still doesn't recognize package

### ISSUE THREAD

**Issue by erezak** [kmontocam/nvim-conda#18]
My setup uses lsp-zero and Mason:

return {
	{'williamboman/mason.nvim'},
	{'williamboman/mason-lspconfig.nvim'},

	{'VonHeikemen/lsp-zero.nvim', branch = 'v3.x'},
	{'neovim/nvim-lspconfig'},
	{'hrsh7th/cmp-nvim-lsp'},
	{'hrsh7th/nvim-cmp'},
	{'L3MON4D3/LuaSnip'},
}

The python lsp is pyright.

**Comment by kmontocam** [comment]
Hello, I personally haven't tried lsp-zero, and I didn't include that on my testings. I will give it a look to find what is going on

**Comment by hyperion2144** [comment]
Maybe you can use [venv-selector.nvim](https://github.com/linux-cultist/venv-selector.nvim), this plug can activate the virutal env include conda。

**Comment by erezak** [comment]
I've moved to poetry, which solves most issues for me. Thanks!
