### ISSUE TITLE
Wrong repo name for lazy.nvim example

### ISSUE THREAD

**Issue by Vidarrwin** [kmontocam/nvim-conda#7]
The name of the git repo given in the lazy-vim example is inverted, writing it to nvim gives an error.
I used this instead and it worked like a charm :)

```lua
return {
	"kmontocam/nvim-conda",
	dependencies = { "nvim-lua/plenary.nvim" },
    }
```

Thank you for your work !

**Comment by kmontocam** [comment]
Thank you for noticing and leaving the comment!
